# Generated by Django 4.2 on 2023-04-18 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('renting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='sector',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='renting.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='publishingpayment',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.landlord', verbose_name='Landlord'),
        ),
        migrations.AddField(
            model_name='publishingpayment',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='renting.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='renting.property', verbose_name='Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.cell', verbose_name='Cell'),
        ),
        migrations.AddField(
            model_name='property',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.district', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='property',
            name='landlord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='renting.landlord', verbose_name='Landlord'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='renting.propertytype', verbose_name='Property Type'),
        ),
        migrations.AddField(
            model_name='property',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='property',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='renting.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='landlord',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landlords', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='renting.province', verbose_name='Province'),
        ),
        migrations.AddField(
            model_name='cell',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='renting.sector', verbose_name='Sector'),
        ),
    ]
