# Generated by Django 4.2 on 2023-04-22 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renting', '0005_alter_userlocation_cell_alter_userlocation_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlord',
            name='profile_image',
            field=models.ImageField(upload_to='profile/landlords', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Select Gender'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile/managers', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floors',
            field=models.PositiveIntegerField(null=True, verbose_name='Floors'),
        ),
    ]
